// Lesson data for all 15 Minor Free Courses — VVIP quality, 1-2 lessons each
const lessons = [];

function add(course, title, duration, order, parts, quiz) {
  lessons.push({
    course,
    title,
    content: parts.join('\n\n') + '\n\n' + quiz.join('\n'),
    duration,
    order,
  });
}

// ── 1. AI Fluency ──
add('AI Fluency', 'Understanding AI: Core Concepts and Real-World Impact', 25, 1, [
  '## Understanding AI: Core Concepts and Real-World Impact',
  'Artificial Intelligence (AI) is the simulation of human intelligence by machines, from Netflix recommendations to autonomous vehicles and medical diagnosis. AI systems perceive their environment, reason, and take actions to achieve goals.',
  'The field evolved from 1950s symbolic reasoning through 1990s machine learning to todays deep learning era, where neural networks achieve superhuman performance in image classification and language understanding.',
  '### The Three Types of AI',
  '**Narrow AI:** Designed for one specific task (facial recognition, spam filters). This is 100% of commercial AI today.',
  '**AGI:** Human-level intelligence across all domains. Remains a research goal.',
  '**Superintelligence:** AI surpassing humans across all domains. Raises profound questions about control and alignment.',
  '### How AI Systems Learn',
  '| Paradigm | Description | Example |',
  '|---|---|---|',
  '| Supervised | Trains on labeled input-output pairs | Spam classification |',
  '| Unsupervised | Finds hidden patterns in unlabeled data | Customer segmentation |',
  '| Reinforcement | Learns through rewards and penalties | AlphaGo, robotics |',
  '### Real-World Applications',
  'Healthcare: detecting tumors with superhuman accuracy. Finance: real-time fraud detection. Transportation: self-driving cars. Education: adaptive learning paths. Creative arts: generative images, music, and code.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. What distinguishes Narrow AI from AGI?**',
  'A) Narrow AI can only process text',
  'B) Narrow AI is designed for specific tasks; AGI matches human intelligence across all domains',
  'C) Narrow AI needs no data; AGI needs billions of examples',
  'D) Narrow AI is from the 1950s; AGI emerged in the 2020s',
  '',
  '> **Answer:** B) Narrow AI excels at a single domain, whereas AGI would match human cognitive ability across any intellectual task.',
  '',
  '**Q2. Which paradigm learns through rewards and penalties?**',
  'A) Supervised',
  'B) Unsupervised',
  'C) Reinforcement',
  'D) Transfer',
  '',
  '> **Answer:** C) Reinforcement Learning uses an agent that receives rewards or penalties for actions, learning optimal behavior through trial and error.',
]);

// ── 2. Prompt Engineering ──
add('Prompt Engineering', 'Crafting Effective Prompts: Techniques for Reliable AI Output', 30, 1, [
  '## Crafting Effective Prompts: Techniques for Reliable AI Output',
  'Prompt Engineering designs input prompts to consistently produce desired outputs from LLMs. This is one of the most valuable AI skills.',
  'LLMs are next-token predictors. The structure and specificity of your prompt directly shapes the quality of the response.',
  '### The Five Pillars',
  '1. **Role Assignment:** Define who the AI should be\u2014senior engineer, teacher, researcher.',
  '2. **Context Provision:** Supply all relevant background information.',
  '3. **Clear Task:** Use imperative verbs: Write, Explain, Analyze, Generate.',
  '4. **Output Format:** Specify structure: JSON, bullet points, table.',
  '5. **Constraints:** Set boundaries: 150 words max, no jargon, say "I don\'t know" if uncertain.',
  '### Advanced Patterns',
  '**Chain-of-Thought:** Reason step-by-step. Dramatically improves accuracy on complex reasoning.',
  '**Few-Shot:** Provide 2\u20133 examples before the actual query.',
  '**Structured Output:** Define exact schema in the prompt for consistent results.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. Why does role assignment improve prompt quality?**',
  'A) It makes the AI respond faster',
  'B) It primes the model with a specific persona, vocabulary, and knowledge base',
  'C) It bypasses safety filters',
  'D) It reduces tokens',
  '',
  '> **Answer:** B) Role assignment constrains the model to a persona, shaping vocabulary, depth, and prioritization for the task.',
  '',
  '**Q2. What is Chain-of-Thought prompting?**',
  'A) Generating multiple responses and selecting the best',
  'B) Asking the model to reason step-by-step before answering',
  'C) Chaining multiple prompts sequentially',
  'D) Providing examples before the query',
  '',
  '> **Answer:** B) CoT breaks reasoning into intermediate steps, improving accuracy on complex arithmetic, logic, and multi-step problems.',
]);

// ── 3. AI-Assisted Coding ──
add('AI-Assisted Coding', 'Leveraging AI for Code Generation, Debugging, and Refactoring', 30, 1, [
  '## Leveraging AI for Code Generation, Debugging, and Refactoring',
  'AI coding assistants like GitHub Copilot and Cursor are essential developer tools\u2014force multipliers that handle boilerplate, accelerate exploration, and catch bugs.',
  'They are trained on vast public code corpora, learning syntax patterns, API conventions, and common algorithms.',
  '### Best Practices',
  '**Clear Specifications:** "Write a TypeScript function that sorts users by last_name ascending, handling nulls at the end" produces better code than "Write a sort function."',
  '**Iterate and Review:** Treat AI output as a first draft. Check edge cases, security, and performance. Refine the prompt and regenerate.',
  '### Debugging with AI',
  'Paste error messages with surrounding code. AI identifies root causes, suggests fixes, and explains reasoning\u2014often faster than manual debugging.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. What most impacts AI-generated code quality?**',
  'A) Programming language',
  'B) Specificity and clarity of the prompt',
  'C) Model size',
  'D) Internet speed',
  '',
  '> **Answer:** B) Code quality is directly proportional to prompt specificity. Well-structured prompts with edge cases and types produce far more reliable code.',
  '',
  '**Q2. How should developers treat AI-generated code?**',
  'A) Use it as-is',
  'B) Review critically for edge cases, security, and performance as the first draft',
  'C) Only use for Python',
  'D) Requires a license',
  '',
  '> **Answer:** B) AI code is a starting point requiring the same critical review as any teammate pull request.',
]);

// ── 4. Introduction to LLMs ──
add('Introduction to LLMs', 'How Large Language Models Work: Architecture, Training, and Inference', 25, 1, [
  '## How Large Language Models Work: Architecture, Training, and Inference',
  'LLMs like GPT-4, Claude, and Llama are deep neural networks trained on trillions of words. They learn statistical patterns in language, grammar, and reasoning.',
  '### The Transformer Architecture',
  'Transformers (from "Attention Is All You Need," 2017) process all tokens in parallel using self-attention to weigh word relationships.',
  '**Key components:** Tokenization (subword units), Embeddings (semantic vectors), Self-Attention (pairwise importance scores), Feed-Forward layers (non-linear transformation).',
  '### Training Process',
  '1. **Pre-training:** Predict next token on trillions of tokens. Unsupervised.',
  '2. **SFT:** Fine-tune on human instruction-response pairs.',
  '3. **RLHF:** Human raters compare outputs, train a reward model, and optimize the LLM to maximize reward\u2014making models helpful, harmless, and honest.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. What allows Transformers to process all words simultaneously?**',
  'A) Recurrent connections',
  'B) Self-attention',
  'C) Convolutions',
  'D) LSTM gates',
  '',
  '> **Answer:** B) Self-attention computes importance between every pair of tokens, enabling parallel processing and long-range dependency capture.',
  '',
  '**Q2. What is the purpose of RLHF?**',
  'A) Reduce model size',
  'B) Align the model with human values through human-rated output comparisons',
  'C) Increase vocabulary',
  'D) Train on more data',
  '',
  '> **Answer:** B) RLHF uses human comparisons to train a reward model, then optimizes the LLM to produce outputs humans prefer.',
]);

// ── 5. AI Safety & Responsible AI ──
add('AI Safety & Responsible AI', 'Ethics, Bias, and Safety in AI Systems', 30, 1, [
  '## Ethics, Bias, and Safety in AI Systems',
  'AI safety must be integrated throughout the AI lifecycle. Bias, transparency, and accountability are critical concerns.',
  '### Sources of Bias',
  '**Training Data Bias:** Historical biases in data are learned and amplified by models.',
  '**Labeling Bias:** Human annotators bring unconscious bias. Facial recognition had higher error rates for women with darker skin due to non-representative training data.',
  '**Algorithmic Amplification:** Optimization for engagement can amplify sensationalist content.',
  '### Responsible AI Framework',
  '**Fairness:** Diverse data, bias testing, continuous monitoring. **Transparency:** Disclose AI interaction and limitations. **Accountability:** Clear ownership for outcomes. **Privacy:** Data minimization and user control. **Robustness:** Reliable performance under varied conditions.',
  '### Generative AI Safety',
  'Hallucination (confident falsehoods), prompt injection (bypassing guardrails), and misuse (deepfakes, phishing) require robust safeguards.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. Which is NOT a primary source of AI bias?**',
  'A) Historical training data biases',
  'B) Human annotator bias',
  'C) Programming language used to implement the model',
  'D) Algorithmic design optimizing wrong metrics',
  '',
  '> **Answer:** C) Programming language does not introduce bias. Sources are data, labeling, and algorithmic design.',
  '',
  '**Q2. Why is transparency important in AI?**',
  'A) Increases accuracy',
  'B) Enables informed decisions about AI interaction and limitations',
  'C) Reduces cost',
  'D) Improves speed',
  '',
  '> **Answer:** B) Transparency communicates AI interaction, capabilities, and limitations, enabling informed consent and trust.',
]);

// ── 6. Claude Fundamentals ──
add('Claude Fundamentals', 'Mastering Claude: Capabilities, Best Practices, and Advanced Features', 30, 1, [
  '## Mastering Claude: Capabilities, Best Practices, and Advanced Features',
  'Claude is a state-of-the-art AI assistant built by Anthropic, designed to be helpful, harmless, and honest. Understanding its unique capabilities enables you to get the most out of every interaction.',
  '### Claude\'s Key Strengths',
  '**Long Context Window:** Claude processes up to 200K tokens\u2014analyzing entire codebases, research papers, or book-length documents in a single conversation.',
  '**Nuanced Reasoning:** Claude excels at multi-step reasoning, nuanced analysis, and handling ambiguous questions with appropriate hedging.',
  '**Safety-First Design:** Constitutional AI training ensures Claude refuses harmful requests while explaining why, making it ideal for sensitive domains like healthcare and education.',
  '### Best Practices for Claude',
  '**Be Specific:** Vague prompts yield vague answers. State the format, depth, and audience for the response.',
  '**Use Prefacing:** Start with high-level context before diving into specifics. "I\'m writing a beginner\'s guide to SQL. Here\'s what I have so far..."',
  '**Iterate:** Treat Claude\'s first response as a draft. Refine your request based on the output.',
  '### Advanced Features',
  '**Projects:** Organize conversations around topics with shared knowledge. **Artifacts:** Generate standalone documents, code, or analysis in a dedicated canvas. **Custom Instructions:** Set persistent preferences for tone, depth, and style across all conversations.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. What is Claude\'s maximum context window?**',
  'A) 32K tokens',
  'B) 100K tokens',
  'C) 200K tokens',
  'D) 1M tokens',
  '',
  '> **Answer:** C) Claude can process up to 200K tokens in a single conversation, enabling analysis of extremely long documents.',
  '',
  '**Q2. What makes Claude\'s safety approach unique?**',
  'A) It refuses all requests',
  'B) Constitutional AI training aligns it to be helpful, harmless, and honest',
  'C) It only answers technical questions',
  'D) It requires human oversight for every response',
  '',
  '> **Answer:** B) Constitutional AI uses a set of principles to guide Claude\'s behavior, making it inherently safety-conscious by design.',
]);

// ── 7. AI Collaboration Techniques ──
add('AI Collaboration Techniques', 'Working with AI as a Partner: Frameworks for Effective Human-AI Collaboration', 25, 1, [
  '## Working with AI as a Partner: Frameworks for Effective Human-AI Collaboration',
  'Treating AI as a collaborator rather than a tool unlocks dramatically better outcomes. The key is understanding when to lead and when to follow the AI\'s suggestions.',
  '### The Co-Creation Framework',
  '**1. Define the Objective:** Clearly articulate what success looks like. "I need a marketing email that increases click-through rates among existing customers."',
  '**2. Brainstorm Together:** Use the AI to generate multiple approaches. Ask for 5 different angles, then pick the strongest direction.',
  '**3. Draft and Refine:** Let the AI produce a first draft. Review critically, then request specific revisions. "Make the tone more formal. Shorten the second paragraph. Add a statistic about retention."',
  '**4. Verify and Polish:** Fact-check claims, test code, and tighten language. The human is always the final quality gate.',
  '### The Centaur vs. Cyborg Models',
  '**Centaur:** Deliberately switch between human and AI tasks. Humans do strategic planning and quality control; AI handles drafting, research, and pattern matching.',
  '**Cyborg:** Seamlessly integrate AI into every part of the workflow, using AI suggestions in real time as you work. Both models are effective for different tasks.',
  '### Common Pitfalls',
  '**Over-reliance:** Using AI answers without verification leads to errors. Always validate. **Underspecification:** Vague requests produce generic output. Invest time in precise prompts. **Confirmation Bias:** Asking leading questions limits AI\u2019s potential. Let the AI challenge your assumptions.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. What is the Centaur model of AI collaboration?**',
  'A) Using multiple AI models simultaneously',
  'B) Deliberately switching between human-led and AI-led tasks based on strengths',
  'C) Letting AI make all decisions independently',
  'D) Training AI to mimic human behavior exactly',
  '',
  '> **Answer:** B) The Centaur model assigns strategic and quality-control tasks to humans while delegating drafting, research, and pattern recognition to AI.',
  '',
  '**Q2. What is the most common mistake in AI collaboration?**',
  'A) Using too many prompts',
  'B) Over-reliance on AI output without verification',
  'C) Asking yes/no questions',
  'D) Using complex vocabulary in prompts',
  '',
  '> **Answer:** B) Users often trust AI output without verification, leading to errors. AI should be treated as a first draft that requires human review.',
]);

// ── 8. Git & GitHub Fundamentals ──
add('Git & GitHub Fundamentals', 'Version Control with Git: Essential Commands and Collaborative Workflows', 35, 1, [
  '## Version Control with Git: Essential Commands and Collaborative Workflows',
  'Git is the industry-standard distributed version control system. Every developer must know Git to collaborate effectively on any codebase.',
  '### Core Concepts',
  '**Repository:** A folder tracked by Git containing the entire project history. **Commit:** A snapshot of changes with a unique hash. **Branch:** An independent line of development. **Remote:** A hosted copy of the repository (GitHub, GitLab).',
  '### Essential Commands',
  '| Command | Purpose |',
  '|---|---|',
  '| git init | Create a new repository |',
  '| git clone <url> | Copy a remote repository locally |',
  '| git add <file> | Stage changes for commit |',
  '| git commit -m "message" | Commit staged changes with a message |',
  '| git push | Send local commits to the remote |',
  '| git pull | Fetch and merge remote changes |',
  '| git branch | List, create, or delete branches |',
  '| git merge <branch> | Merge another branch into the current one |',
  '### Collaborative Workflow (GitHub Flow)',
  '1. Create a feature branch from main: `git checkout -b feature/new-feature`',
  '2. Make changes and commit: `git commit -m "Add new feature"`',
  '3. Push the branch: `git push origin feature/new-feature`',
  '4. Open a Pull Request on GitHub for code review.',
  '5. Merge the PR after approval and delete the branch.',
  '### Best Practices',
  'Write clear, descriptive commit messages. Commit early and often. Pull before pushing to avoid conflicts. Use .gitignore to exclude build artifacts, dependencies, and secrets. Never commit API keys or passwords.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. What Git command creates a copy of a remote repository?**',
  'A) git fork',
  'B) git clone',
  'C) git copy',
  'D) git remote',
  '',
  '> **Answer:** B) `git clone <url>` downloads a remote repository with its full history to your local machine.',
  '',
  '**Q2. What is a Pull Request used for?**',
  'A) Requesting access to a repository',
  'B) Proposing changes for code review before merging',
  'C) Pulling changes from a local branch',
  'D) Requesting help from maintainers',
  '',
  '> **Answer:** B) A Pull Request proposes changes from a feature branch for team review, discussion, and approval before merging into the main branch.',
]);

// ── 9. Linux & Command Line Basics ──
add('Linux & Command Line Basics', 'Navigating the Terminal: Essential Linux Commands for Developers', 30, 1, [
  '## Navigating the Terminal: Essential Linux Commands for Developers',
  'The command line is the developer\'s most powerful tool. Linux commands give you granular control over files, processes, and system resources.',
  '### File System Navigation',
  '| Command | Description |',
  '|---|---|',
  '| pwd | Print working directory |',
  '| ls | List directory contents (use -la for details) |',
  '| cd <dir> | Change directory |',
  '| mkdir <name> | Create a directory |',
  '| rm <file> | Remove a file (-r for directories) |',
  '| cp <src> <dst> | Copy files |',
  '| mv <src> <dst> | Move or rename files |',
  '| cat <file> | Print file contents |',
  '| less <file> | View file with scrolling |',
  '### File Permissions',
  'Linux uses a three-level permission system: Owner, Group, and Others. Each level has read (r), write (w), and execute (x) permissions. View with `ls -l` and modify with `chmod`.',
  '### Process Management',
  'Use `ps` to list processes, `top` or `htop` for real-time monitoring, and `kill` to terminate processes. Append `&` to run a command in the background.',
  '### Pipes and Redirection',
  'Chain commands with `|` to pass output between them. Redirect output with `>` (overwrite) or `>>` (append). Example: `grep error log.txt | sort | uniq -c | sort -nr`',
  '### Package Management',
  'Install software with `apt` (Debian/Ubuntu), `yum` (RHEL), or `brew` (macOS). Always update package lists before installing: `sudo apt update && sudo apt install <package>`.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. What does the command `ls -la` do?**',
  'A) List files in long format including hidden files',
  'B) List only directories',
  'C) List files sorted by size',
  'D) List files with full paths',
  '',
  '> **Answer:** A) The -l flag shows detailed info (permissions, owner, size, date), and -a shows hidden files (those starting with a dot).',
  '',
  '**Q2. How do you chain commands so the output of one feeds into the next?**',
  'A) Using the > operator',
  'B) Using the | pipe operator',
  'C) Using the & operator',
  'D) Using the && operator',
  '',
  '> **Answer:** B) The pipe operator `|` passes the standard output of the left command as standard input to the right command.',
]);

// ── 10. API Fundamentals ──
add('API Fundamentals', 'Understanding REST APIs: Requests, Responses, and Integration Patterns', 30, 1, [
  '## Understanding REST APIs: Requests, Responses, and Integration Patterns',
  'APIs (Application Programming Interfaces) are how software systems communicate. REST APIs dominate modern web development, powering everything from mobile apps to cloud services.',
  '### What is an API?',
  'An API defines a contract: "If you send me a request in this format, I will return a response in that format." APIs abstract complexity\u2014you don\'t need to know how a service works internally to use it.',
  '### REST Principles',
  '**Stateless:** Each request contains all information needed. The server doesn\'t store session state.',
  '**Resource-Based:** Each endpoint represents a resource (/users, /products, /orders).',
  '**HTTP Methods:GET:** Retrieve a resource. **POST:** Create a resource. **PUT:** Update/replace a resource. **PATCH:** Partial update. **DELETE:** Remove a resource.',
  '**Status Codes:200 OK:** Success. **201 Created:** Resource created. **400 Bad Request:** Client error. **401 Unauthorized:** Authentication needed. **404 Not Found:** Resource doesn\'t exist. **500 Internal Server Error:** Server failure.',
  '### API Authentication',
  '**API Keys:** Simple token in the header. **Bearer Tokens (JWT):** Signed tokens containing user claims. **OAuth 2.0:** Delegated authorization flow for third-party access.',
  '### Best Practices',
  'Version your APIs (/v1/users). Use consistent naming conventions (plural nouns, kebab-case). Implement rate limiting. Return meaningful error messages. Document with OpenAPI/Swagger.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. Which HTTP method is used to create a new resource?**',
  'A) GET',
  'B) POST',
  'C) PUT',
  'D) DELETE',
  '',
  '> **Answer:** B) POST sends data to the server to create a new resource. PUT is for full updates, PATCH for partial updates.',
  '',
  '**Q2. What does a 401 status code indicate?**',
  'A) The resource was not found',
  'B) The request was malformed',
  'C) The client is not authenticated',
  'D) The server encountered an error',
  '',
  '> **Answer:** C) 401 Unauthorized means the client must provide valid authentication credentials before accessing the resource.',
]);

// ── 11. Database Fundamentals ──
add('Database Fundamentals', 'Relational Databases and SQL: Modeling, Querying, and Optimization', 35, 1, [
  '## Relational Databases and SQL: Modeling, Querying, and Optimization',
  'Relational databases organize data into tables with rows and columns. SQL is the universal language for querying and manipulating that data.',
  '### Core Concepts',
  '**Tables:** Entities like users, orders, or products. **Rows:** Individual records. **Columns:** Attributes of a record. **Primary Key:** Unique identifier for each row. **Foreign Key:** Links rows across tables for referential integrity.',
  '### SQL Categories',
  '| Category | Purpose | Example Commands |',
  '|---|---|---|',
  '| DDL | Define structure | CREATE, ALTER, DROP |',
  '| DML | Manipulate data | INSERT, UPDATE, DELETE |',
  '| DQL | Query data | SELECT |',
  '| DCL | Control access | GRANT, REVOKE |',
  '### Essential Queries',
  '`SELECT * FROM users WHERE age > 18 ORDER BY name LIMIT 10;`',
  '`INSERT INTO products (name, price) VALUES (\'Widget\', 9.99);`',
  '`UPDATE orders SET status = \'shipped\' WHERE id = 123;`',
  '`DELETE FROM sessions WHERE expires_at < NOW();`',
  '### Joins',
  '**INNER JOIN:** Only matching rows from both tables. **LEFT JOIN:** All rows from the left table, NULLs where right has no match. **RIGHT JOIN:** All rows from the right table. **FULL JOIN:** All rows from both tables, NULLs where no match.',
  '### Indexing and Performance',
  'Indexes speed up lookups at the cost of write speed. Create indexes on columns used in WHERE, JOIN, and ORDER BY clauses. Use EXPLAIN to analyze query plans.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. What SQL clause is used to filter rows?**',
  'A) ORDER BY',
  'B) GROUP BY',
  'C) WHERE',
  'D) HAVING',
  '',
  '> **Answer:** C) WHERE filters rows before grouping. HAVING filters after grouping. ORDER BY sorts results.',
  '',
  '**Q2. What does a LEFT JOIN return?**',
  'A) Only rows that exist in both tables',
  'B) All rows from the left table and matching rows from the right',
  'C) All rows from both tables regardless of matches',
  'D) Only rows from the left table',
  '',
  '> **Answer:** B) LEFT JOIN returns every row from the left table, with matching data from the right table or NULL when no match exists.',
]);

// ── 12. Software Engineering Fundamentals ──
add('Software Engineering Fundamentals', 'The Software Development Lifecycle: Methodologies, Architecture, and Best Practices', 30, 1, [
  '## The Software Development Lifecycle: Methodologies, Architecture, and Best Practices',
  'Software engineering transforms user needs into reliable, maintainable software systems through disciplined processes and practices.',
  '### The Software Development Lifecycle (SDLC)',
  '1. **Requirements:** Gather and document what users need.',
  '2. **Design:** Architect the system, choose technologies, design data models.',
  '3. **Implementation:** Write code following design specifications.',
  '4. **Testing:** Verify correctness through unit, integration, and end-to-end tests.',
  '5. **Deployment:** Release to production environments.',
  '6. **Maintenance:** Monitor, fix bugs, and add features iteratively.',
  '### Development Methodologies',
  '**Waterfall:** Sequential phases with no backtracking. Suitable for well-understood projects with fixed requirements.',
  '**Agile:** Iterative development with 1\u20132 week sprints, continuous feedback, and adaptive planning. Scrum and Kanban are popular frameworks.',
  '### Architecture Patterns',
  '**Monolithic:** Single deployable unit. Simple initially but hard to scale. **Microservices:** Independent services communicating via APIs. Scalable but operationally complex. **Serverless:** Functions deployed on-demand. No infrastructure management.',
  '### Code Quality',
  'Write clean, readable code. Follow DRY (Don\'t Repeat Yourself) and SOLID principles. Use version control. Write automated tests. Conduct code reviews. Document rationale, not just syntax.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. Which SDLC phase comes after Implementation?**',
  'A) Requirements',
  'B) Design',
  'C) Testing',
  'D) Deployment',
  '',
  '> **Answer:** C) Testing verifies the implementation is correct before deployment to production.',
  '',
  '**Q2. What is the key difference between Waterfall and Agile?**',
  'A) Waterfall uses tests; Agile doesnt',
  'B) Waterfall is sequential and rigid; Agile is iterative and adaptive',
  'C) Waterfall is only for small projects',
  'D) Agile requires specific programming languages',
  '',
  '> **Answer:** B) Waterfall completes each phase fully before moving on, while Agile iterates rapidly with ongoing feedback and requirements refinement.',
]);

// ── 13. Cloud Computing Fundamentals ──
add('Cloud Computing Fundamentals', 'Cloud Models, Deployment Strategies, and Core Services', 30, 1, [
  '## Cloud Computing Fundamentals: Models, Deployment Strategies, and Core Services',
  'Cloud computing delivers compute, storage, and networking resources on-demand over the internet. It eliminates upfront hardware investment and enables elastic scaling.',
  '### Service Models',
  '| Model | What You Get | Example |',
  '|---|---|---|',
  '| IaaS | Virtual servers, storage, networking | AWS EC2, Google Compute Engine |',
  '| PaaS | Platform to deploy applications | Heroku, Vercel, Supabase |',
  '| SaaS | Ready-to-use software applications | Gmail, Notion, Slack |',
  '### Deployment Models',
  '**Public Cloud:** Shared infrastructure over the internet (AWS, Azure, GCP). Most cost-effective.',
  '**Private Cloud:** Dedicated infrastructure for a single organization. Highest control and security.',
  '**Hybrid Cloud:** Mix of public and private, allowing data and applications to share resources.',
  '### Core Cloud Services',
  '**Compute:** Virtual machines (EC2), containers (ECS, Kubernetes), serverless (Lambda).',
  '**Storage:** Object storage (S3), block storage (EBS), databases (RDS, DynamoDB).',
  '**Networking:** Virtual networks (VPC), load balancers, CDN (CloudFront).',
  '### Key Benefits',
  '**Scalability:** Resources scale up or down automatically. **Pay-as-you-go:** Only pay for what you use. **Global Reach:** Deploy in data centers worldwide. **Reliability:** Built-in redundancy and disaster recovery.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. What cloud model provides virtual servers and storage?**',
  'A) SaaS',
  'B) PaaS',
  'C) IaaS',
  'D) FaaS',
  '',
  '> **Answer:** C) IaaS (Infrastructure as a Service) provides raw compute, storage, and networking resources that you manage.',
  '',
  '**Q2. What is a key benefit of cloud computing over on-premises infrastructure?**',
  'A) Lower latency guaranteed',
  'B) Elastic scaling without upfront hardware investment',
  'C) Complete data control',
  'D) No internet required',
  '',
  '> **Answer:** B) Cloud resources scale on-demand and you pay only for what you use, eliminating large capital expenditures on hardware.',
]);

// ── 14. AI Productivity & Automation ──
add('AI Productivity & Automation', 'Automating Workflows with AI: Tools, Strategies, and Real-World Use Cases', 30, 1, [
  '## Automating Workflows with AI: Tools, Strategies, and Real-World Use Cases',
  'AI-powered automation eliminates repetitive tasks, freeing knowledge workers for higher-value strategic thinking. From email drafting to code generation, AI transforms productivity.',
  '### High-Impact Automation Areas',
  '**Email and Communication:** AI drafts responses, summarizes threads, and schedules meetings. Tools like Claude and Grammarly handle tone and clarity.',
  '**Document Processing:** Extract data from invoices, contracts, and reports automatically. AI performs OCR, entity extraction, and summarization in seconds.',
  '**Code and Development:** AI generates boilerplate code, writes unit tests, reviews pull requests, and explains legacy code. GitHub Copilot and Cursor integrate directly into the IDE.',
  '**Data Analysis:** AI generates SQL queries, creates visualizations, and identifies trends in datasets. Natural language interfaces make analytics accessible to non-technical team members.',
  '### Building Automated Workflows',
  '1. **Identify repetitive tasks:** What do you do manually more than once a week?',
  '2. **Choose the right tool:** AI writing assistants, no-code automation (Zapier, Make), or custom scripts.',
  '3. **Design the workflow:** Define triggers, actions, and fallback for edge cases.',
  '4. **Test and refine:** Start with low-risk tasks, verify outputs, and iterate.',
  '### The Human-in-the-Loop Principle',
  'AI automation should always include human oversight for critical decisions. Use AI to handle the 80% routine work, and escalate edge cases, exceptions, and high-stakes decisions to humans.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. What is the first step in building an automated workflow?**',
  'A) Choose an AI tool',
  'B) Identify repetitive, high-frequency tasks',
  'C) Write automation scripts',
  'D) Test the workflow',
  '',
  '> **Answer:** B) Start by identifying tasks you perform manually and frequently. These are the highest-ROI candidates for automation.',
  '',
  '**Q2. What does Human-in-the-Loop mean?**',
  'A) Humans are not needed in automated workflows',
  'B) Critical decisions require human review and approval',
  'C) Humans monitor AI system performance',
  'D) Humans train the AI models',
  '',
  '> **Answer:** B) Human-in-the-Loop ensures that important or ambiguous decisions are reviewed by a human, combining AI efficiency with human judgment.',
]);

// ── 15. Cybersecurity Fundamentals ──
add('Cybersecurity Fundamentals', 'Security Principles, Threat Models, and Defensive Practices', 30, 1, [
  '## Cybersecurity Fundamentals: Security Principles, Threat Models, and Defensive Practices',
  'Cybersecurity protects systems, networks, and data from digital attacks. Every developer must understand security fundamentals to build safe applications.',
  '### The CIA Triad',
  '**Confidentiality:** Data is accessible only to authorized parties. Achieved through encryption and access controls.',
  '**Integrity:** Data is accurate and unmodified by unauthorized actors. Achieved through hashing, checksums, and digital signatures.',
  '**Availability:** Systems and data are accessible when needed. Achieved through redundancy, backups, and DDoS protection.',
  '### Common Threat Types',
  '**Phishing:** Deceptive messages tricking users into revealing credentials. The most common attack vector.',
  '**SQL Injection:** Malicious SQL inserted into user input. Prevented by parameterized queries.',
  '**Cross-Site Scripting (XSS):** Malicious scripts injected into web pages. Prevented by input sanitization and Content Security Policy headers.',
  '**Man-in-the-Middle:** Attacker intercepts communication. Prevented by HTTPS/TLS encryption.',
  '### Defensive Best Practices',
  '**Principle of Least Privilege:** Grant minimum access necessary. **Defense in Depth:** Multiple layers of security. **Regular Updates:** Patch known vulnerabilities. **Strong Authentication:** MFA, password managers, OAuth. **Backups:** 3-2-1 rule (3 copies, 2 media types, 1 offsite).',
  '### Secure Development',
  'Validate all input. Use parameterized queries. Hash passwords (bcrypt, Argon2). Never hardcode secrets. Use environment variables for configuration. Conduct security reviews and penetration testing.',
], [
  '### \u{1F9E0} Quick Knowledge Check',
  '',
  '**Q1. What does the C in the CIA Triad stand for?**',
  'A) Compliance',
  'B) Confidentiality',
  'C) Consistency',
  'D) Control',
  '',
  '> **Answer:** B) Confidentiality ensures data is only accessible to authorized individuals through encryption, access controls, and authentication.',
  '',
  '**Q2. How do you prevent SQL Injection?**',
  'A) Use an ORM',
  'B) Use parameterized queries or prepared statements',
  'C) Validate input length',
  'D) Use a firewall',
  '',
  '> **Answer:** B) Parameterized queries separate SQL logic from data, making it impossible for user input to alter the query structure. ORMs also help but parameterized queries are the direct defense.',
]);

module.exports = lessons;
