-- Seed: IH Academy official courses

INSERT INTO public.courses (title, description, category, level, total_lessons, xp_reward) VALUES
-- Major Paid Courses ($50-$70)
('Frontend Development',
  'Master modern frontend frameworks, responsive design, and browser APIs to build production-grade web applications.',
  'Web Development', 'Advanced', 12, 150),
('Backend Development',
  'Build scalable server-side systems with Node.js, databases, and cloud services for real-world applications.',
  'Web Development', 'Advanced', 12, 150),
('Machine Learning',
  'Dive into supervised and unsupervised learning, neural networks, and model deployment with Python.',
  'AI & Data', 'Advanced', 15, 200),
('Generative AI',
  'Explore transformers, LLMs, diffusion models, and build generative applications from scratch.',
  'AI & Data', 'Advanced', 14, 200),
('Agentic AI',
  'Design autonomous AI agents with tool-use, planning, memory, and multi-agent coordination.',
  'AI & Data', 'Advanced', 16, 250),
('Full-Stack',
  'End-to-end development covering frontend, backend, databases, authentication, and deployment.',
  'Web Development', 'Advanced', 20, 300),
('Generative UI/UX',
  'Design AI-powered interfaces with generative design tools, prototyping, and user-testing workflows.',
  'Design', 'Intermediate', 10, 150),
-- Minor Free Courses ($0)
('AI Fluency',
  'Understand core AI concepts, terminology, and real-world applications without a technical background.',
  'AI Fundamentals', 'Beginner', 4, 50),
('Prompt Engineering',
  'Learn prompt design patterns, chain-of-thought, and advanced techniques to get the best from LLMs.',
  'AI Tools', 'Beginner', 5, 50),
('AI-Assisted Coding',
  'Use AI coding assistants to write, debug, and refactor code faster and more effectively.',
  'AI Tools', 'Beginner', 5, 50),
('Introduction to LLMs',
  'Understand how large language models work, their capabilities, and their limitations.',
  'AI Fundamentals', 'Beginner', 4, 50),
('AI Safety & Responsible AI',
  'Explore bias, alignment, transparency, and ethical considerations in AI development and deployment.',
  'AI Fundamentals', 'Beginner', 4, 50),
('Claude Fundamentals',
  'Get productive with Claude — from conversation basics to project management and custom styles.',
  'AI Tools', 'Beginner', 4, 50),
('AI Collaboration Techniques',
  'Learn workflows to collaborate effectively with AI agents on complex, multi-step tasks.',
  'AI Tools', 'Beginner', 4, 50),
('Git & GitHub Fundamentals',
  'Version control essentials: commits, branching, pull requests, and collaborative workflows.',
  'Tools', 'Beginner', 5, 50),
('Linux & Command Line Basics',
  'Navigate the filesystem, manage processes, and write shell scripts with confidence.',
  'Tools', 'Beginner', 4, 50),
('API Fundamentals',
  'Understand REST, GraphQL, request/response patterns, and how to integrate third-party APIs.',
  'Fundamentals', 'Beginner', 4, 50),
('Database Fundamentals',
  'Learn relational design, SQL queries, and basic data modeling for applications.',
  'Fundamentals', 'Beginner', 5, 50),
('Software Engineering Fundamentals',
  'Master coding best practices, debugging, testing, and software design principles.',
  'Fundamentals', 'Beginner', 6, 75),
('Cloud Computing Fundamentals',
  'Explore cloud models, basic deployment, and infrastructure-as-code concepts.',
  'Fundamentals', 'Beginner', 5, 75),
('AI Productivity & Automation',
  'Automate repetitive tasks and boost productivity using AI-powered tools and agents.',
  'AI Tools', 'Beginner', 4, 50),
('Cybersecurity Fundamentals',
  'Understand threat models, encryption, authentication, and secure coding practices.',
  'Fundamentals', 'Beginner', 5, 75)
ON CONFLICT DO NOTHING;
